// SPDX-FileCopyrightText: 2023 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Theme } from "../styling/theme.slint";

export component AnimationContainer {
    in property <bool> open: false;

    opacity: 0.0;

    i-animation-container := Rectangle {
        width: 25%;
        height: 25%;

        Rectangle {
            width: 100%;
            height: 100%;

            @children
        }

        animate width { duration: Theme.animations.slow; }
        animate height { duration: Theme.animations.slow; }
    }

    states [
        open when root.open : {
            i-animation-container.width: 100%;
            i-animation-container.height: 100%;
            opacity: 1.0;
        }
    ]
}