// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Theme } from "../styling/theme.slint";

component Thumb inherits TouchArea {
    width: 128px;
    height: 32px;

    Rectangle {
        border-radius: 4px;
        width: 100%;
        height: 8px;
        background: Theme.palette.border-brush;
    }
}

export component Container {
    callback close();

    in property <brush> background <=> i-inner-container.background;
    in property <length> border-radius <=> i-inner-container.border-radius;

    i-inner-container := Rectangle {
        y: 0px;
        height: root.height - self.y;

        @children

        Thumb {
            x: (parent.width - self.width) / 2;
            y: 0px;

            moved => {
                i-inner-container.y = min(root.height / 2, max(0px, i-inner-container.y - (self.pressed-y - self.mouse-y)));

                if(i-inner-container.y >= root.width * 0.2) {
                    root.close();
                }
            }

            pointer-event(e) => {
                if(e.kind == PointerEventKind.up) {
                    // FIXME
                    if(i-inner-container.y >= root.width * 0.2) {
                        root.close();
                    }

                    if(i-inner-container.y < root.width * 0.2) {
                        i-inner-container.y = 0;
                    }
                }
            }
        }

        animate y { duration: Theme.animations.fast; }
    }
}