// SPDX-FileCopyrightText: 2023 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Theme } from "../styling/theme.slint";
import { StateArea } from "state_area.slint";

export component ImageButton {
    callback clicked <=> i-state-area.clicked;

    in property <image> background-image <=> i-image.source;

    min-width: 256px;
    min-height: 112px;

    i-container := Rectangle {
        border-width: 4px;
        border-radius: 4px;
        border-color: Theme.palette.border-brush;
        clip: true;

        VerticalLayout {
            padding: i-container.border-width;
            alignment: center;

            HorizontalLayout {
                alignment: center;

                Rectangle {
                    preferred-width: 256px;
                    preferred-height: 112px;

                    i-image := Image {
                        image-fit: contain;
                        width: 100%;
                        height: 100%;
                    }
                    i-state-area := StateArea {
                        border-radius:  i-container.border-radius;
                    }
                }
            }
        }
    }
}