// SPDX-FileCopyrightText: 2023 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Theme } from "../styling/theme.slint";
import { StateArea } from "state_area.slint";

export component ImageButton {
    callback clicked <=> i-state-area.clicked;

    in property <image> background-image <=> i-image.source;
    in property <bool> selected <=> i-state-area.has-focus;

    min-width: 256px;
    min-height: 112px;

    i-container := Rectangle {
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;
        width: 100%;
        height: 100%;
        border-width: 4px;
        border-radius: 4px;
        border-color: Theme.palette.border-brush;
        clip: true;

        VerticalLayout {
            padding: i-container.border-width;
            alignment: center;

            HorizontalLayout {
                alignment: center;

                Rectangle {
                    preferred-width: 256px;
                    preferred-height: 112px;

                    i-image := Image {
                        image-fit: contain;
                        width: 100%;
                        height: 100%;
                    }
                }
            }
        }

        animate width, height { duration: 2 * Theme.animations.medium; easing: cubic-bezier(0.05, 0.7, 0.1, 1.0);  }
    }

    i-state-area := StateArea {
        x: i-container.x;
        y: i-container.y;
        width: i-container.width;
        height: i-container.height;
        border-radius:  i-container.border-radius;
    }

    states [
        pressed when i-state-area.pressed : {
            i-container.width: 110%;
            i-container.height: 110%;
        }
    ]
}