// SPDX-FileCopyrightText: 2023 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Paths } from "../styling/paths.slint";
import { Theme } from "../styling/theme.slint";
import { StateArea } from "state_area.slint";
import { Icon } from "icon.slint";

export component Item {
    callback clicked <=> i-state-area.clicked;

    in property <string> text <=> i-text.text;
    in property <string> description;
    in property <string> additional-description;
    in property <bool> selected <=> i-state-area.has-focus;
    in property <string> icon;
    in property <brush> icon-color;
    in property <bool> has-details;
    in property <bool> decent;

    min-height: 68px;
    opacity: decent ? 0.6 : 1.0;
    padding-left: 64px;
    padding-right: 32px;

    Rectangle {
        x: 0;
        y: 0;
        width: 100%;
        height: 40%;
        background: Theme.palette.items-gradient;
    }

    Rectangle {
        x: 0;
        y: 0;
        width: 100%;
        height: 1px;
        background: Theme.palette.border-brush;
    }

    HorizontalLayout {
        height: 100%;
        padding-left: root.padding-left;
        padding-right: root.padding-right;
        spacing: Theme.spacings.medium;

        if (root.icon != "") : Icon {
            text: root.icon;
            vertical-alignment: center;
            color: root.icon-color;
        }

        i-layout := VerticalLayout {
            horizontal-stretch: 1;
            alignment: center;

            i-text := Text {
                color: Theme.palette.foreground-brush;
                horizontal-alignment: left;
                font-size: Theme.typo.label-list-title.font-size;
                overflow: elide;
            }

            if (root.description != "") : Text {
                text: root.description;
                color: Theme.palette.foreground-brush;
                horizontal-alignment: left;
                font-size: Theme.typo.label-list-description.font-size;
                overflow: elide;
            }

            if (root.additional-description != "") : Text {
                text: root.additional-description;
                color: Theme.palette.foreground-brush;
                horizontal-alignment: left;
                font-size: Theme.typo.label-list-description.font-size;
                overflow: elide;
            }
        }

        if (root.has-details) : Path {
            min-width: 32px;
            height: self.width;
            horizontal-stretch: 0;
            commands: Paths.triangle-right;
            fill: Theme.palette.white-right-gradient;
            y: (parent.height - self.height) / 2;
        }
    }

    i-state-area := StateArea {
        width: 100%;
        height: 100%;
    }
}