// SPDX-FileCopyrightText: 2023 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Theme } from "../styling/theme.slint";

export component ListViewItem {
    in property <string> text <=> i-text.text;

    min-height: 64px;

    Rectangle {
        x: 0;
        y: 0;
        width: 100%;
        height: 40%;
        background: Theme.palette.items-gradient;
    }

    Rectangle {
        x: 0;
        y: 0;
        width: 100%;
        height: 1px;
        background: Theme.palette.border-brush;
    }

    HorizontalLayout {
        height: 100%;
        padding-left: Theme.spacings.large;
        padding-right: Theme.spacings.large;
        spacing: Theme.spacings.medium;

        i-text := Text {
            color: Theme.palette.foreground-brush;
            horizontal-alignment: left;
            vertical-alignment: center;
        }
    }
}

export component ListView {
    Flickable {
        VerticalLayout {
            alignment: start;

            @children
        }
    }
}