// SPDX-FileCopyrightText: 2023 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Theme } from "../styling/theme.slint";
import { PathButton } from "path_button.slint";
import { Paths } from "../styling/paths.slint";

export component PageScrollView {
    callback move-left();
    callback move-right();

    in-out property <int> current-page;
    in property <int> count;

    width: 100%;
    height: 100%;

    i-layout := HorizontalLayout {
        x: -min(max(0px, root.current-page * self.width), root.count * self.width);
        width: 100%;
        height: 100%;

        @children

        animate x { duration: Theme.animations.medium;  }
    }

    if(root.current-page > 0) : PathButton {
        x: Theme.spacings.large;
        path: Paths.triangle-left;
        fill: Theme.palette.gradient-white-left;

        clicked => {
            root.move-left();
        }
    }

    if(root.count > 0 && root.current-page < root.count - 1) : PathButton {
        x: root.width - self.width - Theme.spacings.large;
        path: Paths.triangle-right;
        fill: Theme.palette.gradient-white-right;

        clicked => {
            root.move-right();
        }
    }
}