// SPDX-FileCopyrightText: 2023 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Theme } from "../styling/theme.slint";
import { ImageButton } from "image_button.slint";
import { Container } from "container.slint";

export component PageItem {
    callback clicked <=> i-image-button.clicked;
    callback close <=> i-container.close;

    in property <string> title;
    in property <brush> background: red;
    in property <brush> colorize <=> i-image-button.colorize;
    in property <image> button-image <=> i-image-button.background-image;
    in property <bool> selected <=> i-image-button.selected;

    // prevent click through
    TouchArea {
        width: 100%;
        height: 100%;
    }

    i-container := Container {
        x: Theme.spacings.extra-large;
        y: Theme.spacings.large;
        width: root.width - 2 * Theme.spacings.extra-large;
        height: root.height - self.y;
        background: root.background;
        border-radius: 8px;

        Rectangle {
            y: parent.height - self.height;
            width: 100%;
            height: parent.border-radius;
            background: parent.background;
        }

        HorizontalLayout {
            padding: Theme.spacings.medium;

            Text {
                color: Theme.palette.foreground-brush;
                text: root.title;
                font-size: Theme.typo.label-list-title.font-size;
            }
        }

        VerticalLayout {
            alignment: center;

            HorizontalLayout {
                alignment: center;

                i-image-button := ImageButton {}
            }
        }
    }
}