// SPDX-FileCopyrightText: 2023 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Theme } from "../styling/theme.slint";
import { PathButton } from "path_button.slint";
import { Paths } from "../styling/paths.slint";

export component PageScrollView {
    callback move-left();
    callback move-right();

    in-out property <int> current-page;
    in property <int> count;
    out property <length> viewport-x: i-layout.x;

    width: 100%;
    preferred-height: 100%;

    i-layout := HorizontalLayout {
        x: -min(max(0px, root.current-page * self.width), root.count * self.width);
        width: 100%;
        height: 100%;

        @children

        animate x { duration: 2 * Theme.animations.medium; easing: cubic-bezier(0.05, 0.7, 0.1, 1.0);  }
    }

    if(root.current-page > 0) : PathButton {
        x: Theme.spacings.large;
        path: Paths.triangle-left;
        fill: Theme.palette.white-left-gradient;

        clicked => {
            root.move-left();
        }
    }

    if(root.count > 0 && root.current-page < root.count - 1) : PathButton {
        x: root.width - self.width - Theme.spacings.large;
        path: Paths.triangle-right;
        fill: Theme.palette.white-right-gradient;

        clicked => {
            root.move-right();
        }
    }
}