// SPDX-FileCopyrightText: 2023 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Theme } from "../styling/theme.slint";

export component PageinationBubble {
    in property <bool> selected;

    width: Theme.sizes.pageination-bubble;
    height: Theme.sizes.pageination-bubble;

    i-container := Rectangle {
        width: 100%;
        height: 100%;
        border-width: 1px;
        border-radius: max(self.width, self.height) / 2;
        border-color: white;
    }

    states [
        selected when root.selected : {
            i-container.background: white;
        }
    ]
}

export component Pageination {
    in property <int> count;
    in-out property <int> selected-index;

    horizontal-stretch: 0;

   if (root.count > 1) : VerticalLayout {
        alignment: center;
        spacing: Theme.spacings.small;

        for i in count : PageinationBubble {
            selected: i == root.selected-index;
        }
    }
}