// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Theme } from "../styling/theme.slint";
import { PathButton } from "path_button.slint";
import { Paths } from "../styling/paths.slint";

export component PageScrollView {
    callback moved();

    in-out property <int> selected-page;
    in property <int> count;

    i-flickable := Flickable {
        // need to be non interactive because it causes trouble with the flickable of bubble launcher
        interactive: false;
        viewport-x: -min(max(0px, root.selected-page * self.width), root.count * self.width);

        HorizontalLayout {
            @children
        }

        animate viewport-x { duration: Theme.animations.medium;  }
    }

    if(root.selected-page > 0) : PathButton {
        x: Theme.spacings.large;
        path: Paths.triangle-left;
        fill: Theme.palette.gradient-white-left;

        clicked => {
            root.left();
        }
    }

    if(root.count > 0 && root.selected-page < root.count - 1) : PathButton {
        x: root.width - self.width - Theme.spacings.large;
        path: Paths.triangle-right;
        fill: Theme.palette.gradient-white-right;

        clicked => {
            root.right();
        }
    }

    public function set-selected-page(index: int) {
        if(root.selected-page == index || index < 0 || index >= root.count) {
            return;
        }

        root.selected-page = index;
        root.moved();
    }

    public function left() {
        if(root.selected-page <= 0) {
            return;
        }

        root.selected-page -= 1;
        root.moved();
    }

    public function right() {
        if(root.selected-page >= root.count - 1) {
            return;
        }

        root.selected-page += 1;
        root.moved();
    }
}