// SPDX-FileCopyrightText: 2023 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { StateArea } from "state_area.slint";
import { Theme } from "../styling/theme.slint";

export component RoundButton {
    callback clicked <=> i-state-area.clicked;

    in property <string> text <=> i-text.text;

    min-width: 64px;
    min-height: 64px;

    i-background := Rectangle {
        width: 100%;
        height: 100%;
        border-width: 2px;
        border-radius: max(root.width, root.height) / 2;
        background: Theme.palette.hightlight-brush;
        border-color: Theme.palette.highlight-border-brush;
        drop-shadow-blur: 10px;
        drop-shadow-color:#5bd7fd;

        animate width, height { duration: 2 * Theme.animations.medium; easing: cubic-bezier(0.05, 0.7, 0.1, 1.0);  }
    }

    i-text := Text {
        x: (root.width - self.width) / 2 - 4px;
        y: (root.height - self.height) / 2 + 4px;
        font-size: Theme.typo.label-list-title.font-size;
        color: Theme.palette.foreground-brush;
     }

    i-state-area := StateArea {
        width: i-background.width;
        height: i-background.height;
        border-radius: i-background.border-radius;
    }

    states [
        pressed when i-state-area.pressed : {
            i-background.width: 110%;
            i-background.height: 110%;
        }
    ]
}