// SPDX-FileCopyrightText: 2023 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Theme } from "../styling/theme.slint";

export component StateArea {
    private property <bool> animate-state;
    private property <duration> animation: Theme.animations.extra-slow;
    private property <length> shadow-offset: animate-state ? 4px * abs(sin(360deg * animation-tick() / animation)) : 0;
    private property <float> state-opacity: animate-state ?  abs(sin(360deg * animation-tick() / animation)) : 0;

    callback clicked <=> i-touch-area.clicked;

    in property <length> border-radius;
    in property <bool> has-focus;

    preferred-width: 100%;
    preferred-height: 100%;

    i-shadow := Rectangle {
        x: -shadow-offset;
        y: -shadow-offset;
        width: parent.width + 2 * shadow-offset;
        height: parent.height + 2 * shadow-offset;
        border-radius: root.border-radius + shadow-offset;
        border-width: shadow-offset - 1px;
        opacity: state-opacity;

        animate background { duration: Theme.animations.medium; }
    }

    i-container := Rectangle {
        border-width: 2px;
        opacity: state-opacity;
        border-radius: root.border-radius;
    }

    i-touch-area := TouchArea {
        width: 100%;
        height: 100%;
    }

    states [
        focus when root.has-focus : {
            i-container.border-color: Theme.palette.focus-border-brush;
            i-container.background: Theme.palette.focus-surface-brush;
            i-container.drop-shadow-color: Theme.palette.focus-surface-brush;
            i-shadow.border-color: Theme.palette.focus-surface-brush;
            animate-state: true;
        }
        pressed when i-touch-area.pressed : {
            i-container.background: Theme.palette.pressed-surface-brush;
            state-opacity: 1.0;
        }
    ]
}