// SPDX-FileCopyrightText: 2023 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Theme } from "../styling/theme.slint";
import { RoundButton } from "../widgets/widgets.slint";

export global AppBarAdapter {
    in property <string> current-time;
}

export component AppBarView {
    callback button-clicked <=> i-round-button.clicked;

    in property <string> button-text <=> i-round-button.text;

    min-height: 32px;

    Rectangle {
        width: 100%;
        height: 100%;

        background: Theme.palette.app-bar-brush;
    }

    HorizontalLayout {
        padding-left: 8px;
        padding-right: 8px;
        spacing: 8px;
        width: root.width - i-round-button.width;

        Rectangle {
            horizontal-stretch: 1;
        }

        i-timer := Text {
            text: AppBarAdapter.current-time;
            vertical-alignment: center;
            color: Theme.palette.foreground-brush;
            font-size: Theme.typo.label-list-description.font-size;
        }
    }

    Rectangle {
        width: 100%;
        height: 1px;
        y: root.height - self.height;
        background: Theme.palette.border-brush;
    }

    i-round-button := RoundButton {
        width: 0px;
        height: 0px;
        x: (root.width - self.width + 16px);

        animate width, height { duration: 2 * Theme.animations.medium; easing: cubic-bezier(0.05, 0.7, 0.1, 1.0); }
    }

    states [
        button-visble when i-round-button.text != "": {
            i-round-button.width: 64px;
            i-round-button.height: 64px;
        }
    ]
}