// SPDX-FileCopyrightText: 2023 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Container, PageScrollView, StateArea } from "../widgets/widgets.slint";
import { Theme } from "../styling/theme.slint";
import { Paths } from "../styling/paths.slint";

export struct ListItem {
    title: string,
    description: string,
    selected: bool
}

export component ListViewItem {
    callback clicked <=> i-state-area.clicked;

    in property <string> text <=> i-text.text;
    in property <string> description;
    in property <bool> selected <=> i-state-area.has-focus;

    min-height: 64px;

    Rectangle {
        x: 0;
        y: 0;
        width: 100%;
        height: 40%;
        background: Theme.palette.items-gradient;
    }

    Rectangle {
        x: 0;
        y: 0;
        width: 100%;
        height: 1px;
        background: Theme.palette.border-brush;
    }

    HorizontalLayout {
        height: 100%;
        padding-left: 64px;
        padding-right: 32px;
        spacing: Theme.spacings.medium;

        VerticalLayout {
            horizontal-stretch: 1;
            alignment: center;

            i-text := Text {
                color: Theme.palette.foreground-brush;
                horizontal-alignment: left;
                vertical-alignment: center;
                font-size: Theme.typo.label-list-title.font-size;
            }

            if (description != "") : Text {
                text: root.description;
                color: Theme.palette.foreground-brush;
                horizontal-alignment: left;
                vertical-alignment: center;
                font-size: Theme.typo.label-list-description.font-size;
            }
        }

        Path {
            min-width: 32px;
            height: self.width;
            horizontal-stretch: 0;
            commands: Paths.triangle-right;
            fill: Theme.palette.white-right-gradient;
            y: (parent.height - self.height) / 2;
        }
    }

    i-state-area := StateArea {
        width: 100%;
        height: 100%;
    }
}

export global ListAdapter {
    callback show-details(int /* index */);
    callback move-up();
    callback move-down();

    in property <[[ListItem]]> list-items;
    in-out property <length> item-height;
    in property <string> title;
    in property <brush> background;
}

export component ListView {
    callback close <=> i-container.close;

    i-container := Container {
        background: ListAdapter.background;
        preferred-width: 100%;
        preferred-height: 100%;

        VerticalLayout {
            padding-top: 32px;

            Text {
                vertical-stretch: 0;
                color: Theme.palette.foreground-brush;
                font-size: Theme.typo.label-list-title.font-size;
                horizontal-alignment: center;
                vertical-alignment: center;
                text: ListAdapter.title;
            }

            i-page-scroll-view := PageScrollView {
                width: 100%;
                vertical-stretch: 1;

                HorizontalLayout {
                    for list[list-index] in ListAdapter.list-items : Flickable {
                        width: i-page-scroll-view.width;
                        height: i-page-scroll-view.height;

                        VerticalLayout {
                            padding-top: 32px;
                            padding-left: 32px;
                            padding-right: 32px;
                            alignment: start;

                            for item[index] in list : ListViewItem {
                                text: item.title;
                                selected: item.selected;
                                description: item.description;

                                clicked => {
                                    ListAdapter.show-details(index);
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}