// SPDX-FileCopyrightText: 2023 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Container, PageScrollView, ListViewItem } from "../widgets/widgets.slint";

export struct Game {
    title: string,
    selected: bool
}

export global TrophiesAdapter {
    callback game-clicked(int /* index */);

    in property <[Game]> games;
}

export component TrophiesView {
    callback close <=> i-container.close;

    width: 100%;
    height: 100%;

    i-container := Container {
        background: green;

        PageScrollView {
            width: 100%;
            height: 100%;

            Flickable {
                width: root.width;
                height: root.height;

                VerticalLayout {
                    padding-top: 32px;
                    alignment: start;

                    for game[index] in TrophiesAdapter.games : ListViewItem {
                        text: game.title;
                    }
                }
            }
        }
    }
}