// SPDX-FileCopyrightText: 2023 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Container, PageScrollView, ListView, ListViewItem } from "../widgets/widgets.slint";

export struct Game {
    title: string
}

export global TrophiesAdapter {
    in property <[Game]> games;
}

export component TrophiesView {
    callback close <=> i-container.close;

    width: 100%;
    height: 100%;

    i-container := Container {
        background: green;

        PageScrollView {
            width: 100%;
            height: 100%;

            VerticalLayout {
                width: root.width;
                height: root.height;
                alignment: start;
                for game in TrophiesAdapter.games : ListViewItem {
                    text: game.title;
                }
            }
            // ListView {
            //     width: root.width;
            //     height: root.height;

            //     HorizontalLayout {

            //     }


            // }
        }
    }
}