// SPDX-FileCopyrightText: 2023 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

struct Spacings {
    small: length,
    medium: length,
    large: length,
    extra-large: length
}

struct Sizes {
    bubble: length,
    pageination-bubble: length,
}

struct Animations {
    extra-slow: duration,
    medium: duration,
    fast: duration,
    slow: duration
}

struct Palette {
    gradient-white-right: brush,
    gradient-white-left: brush,
    background-gradient: brush,
    items-gradient: brush,
    focus-border-brush: brush,
    focus-surface-brush: brush,
    pressed-surface-brush: brush,
    border-brush: brush,
    foreground-brush: brush
}

export global Theme {
    out property <Sizes> sizes: {
        bubble: 128px,
        pageination-bubble: 8px,
    };

    out property <Spacings> spacings: {
        small: 4px,
        medium: 8px,
        large: 16px,
        extra-large: 64px,
    };

    out property <Animations> animations: {
        extra-slow: 4s,
        fast: 150ms,
        medium: 200ms,
        slow: 500ms,
    };

    out property <Palette> palette: {
        gradient-white-right: @linear-gradient(90deg, #ffffff00 0%, #ffffff 100%),
        gradient-white-left: @linear-gradient(90deg, #ffffff 0%, #ffffff00 100%),
        background-gradient: @linear-gradient(180deg, #6d717c 0%, #96a2ae 100%),
        items-gradient: @linear-gradient(180deg, #ffffff78 0%, #ffffff2d 100%),
        focus-border-brush: #32edff,
        focus-surface-brush: #32edff80,
        pressed-surface-brush: #ffffff80,
        border-brush: #ffffff,
        foreground-brush: #ffffff
    };
}