// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Theme } from "theme.slint";
import { StateArea } from "state_area.slint";
import { BubbleLauncher, BubblePage, Bubble } from "bubble_launcher.slint";
import { Pageination } from "pageination.slint";
import { PageScrollView } from "page_scroll_view.slint";
import { PageItem, Page } from "page.slint";

export global PageAdapter {
    callback open-page(string /* id */) -> bool;
    callback close-page(string /* id */);

    in-out property <[Page]> model: [
        {
            title: "Trophies",
            color: #ff0000,
        }
    ];
}

export global BubbleAdapter {
    in-out property <[[Bubble]]> model: [
        [
            { title: "Minetest", icon: @image-url("minetest.png"), row: 0, column: 0 },
            { title: "Trophies", row: 0, column: 1 },
            { title: "Item 3", row: 0, column: 2 },
            { title: "Item 4", row: 1, column: 0 },
            { title: "Item 5", row: 1, column: 1 },
            { title: "Item 6", row: 1, column: 2 },
            { title: "Item 7", row: 1, column: 3 },
            { title: "Item 8", row: 2, column: 0 },
            { title: "Item 9", row: 2, column: 1 },
            { title: "Item 10", row: 2, column: 2, filler: false },
        ],
        [
            { title: "Item 1", row: 0, column: 0 },
            { title: "Item 1", row: 0, column: 0 },
            { row: 0, column: 1, filler: true },
            { title: "Item 3", row: 0, column: 2 },
            { title: "Item 4", row: 1, column: 0 },
            { title: "Item 5", row: 1, column: 1 },
            { row: 1, column: 2, filler: true },
            { title: "Item 7", row: 1, column: 3 },
            { title: "Item 8", row: 2, column: 0 },
            { title: "Item 9", row: 2, column: 1 },
            { row: 2, column: 2, filler: true },
            { row: 2, column: 3, filler: true },
        ]
    ];
}

export component AppWindow inherits Window {
    callback open-page <=> PageAdapter.open-page;
    callback close-page <=> PageAdapter.close-page;

    in-out property <bool> open-pages;

    in-out property <[[Bubble]]> bubbles <=> BubbleAdapter.model;
    in-out property <[Page]> pages <=> PageAdapter.model;

    title: "vita";
    width: 960px;
    height: 544px;
    forward-focus: i-focus-scope;

    i-page-scroll-view := PageScrollView {
        count: 1 + PageAdapter.model.length;

        HorizontalLayout {
            padding-left: Theme.spacings.medium;
            width: root.width;
            height: root.height;

            i-pageination := Pageination {
                count: i-bubble-launcher.model.length;
                selected-index: i-bubble-launcher.selected-page;
            }

            i-bubble-launcher := BubbleLauncher {
                model <=> BubbleAdapter.model;

                page-right => {
                    if(i-page-scroll-view.count == 1) {
                        return false;
                    }

                    i-page-scroll-view.right();
                    return true;
                }

                open-item(id) => {
                    if(PageAdapter.open-page(id)) {
                        i-page-scroll-view.right();
                    }
                }
            }
        }

        for page in PageAdapter.model : PageItem {
            width: root.width;
            height: root.height;
            title: page.title;
            background: page.color;
        }

        moved => {
            // remove inner focus
            i-focus-scope.focus();
            i-bubble-launcher.remove-focus();
        }
    }

    i-focus-scope := FocusScope {
        width: 0px;

        key-pressed(e) => {
            if((e.text == Key.DownArrow || e.text == Key.UpArrow || e.text == Key.LeftArrow || ( e.text == Key.RightArrow &&  i-page-scroll-view.count == 1))
                && i-page-scroll-view.selected-page == 0) {
                i-bubble-launcher.focus-first();
                return accept;
            }

            if(e.text == Key.LeftArrow) {
                i-page-scroll-view.left();
            }

            if(e.text == Key.RightArrow) {
                i-page-scroll-view.right();
            }

            reject
        }
    }
}
