// SPDX-FileCopyrightText: 2023 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Theme } from "styling/theme.slint";
import { Icons } from "styling/icons.slint";
import { StateArea, BubbleLauncher, Bubble, Pageination, PageScrollView, PageItem } from "widgets/widgets.slint";

import { LauncherView, LauncherAdapter, ListAdapter, ListItem, AppBarAdapter, NotificationAdapter, NotificationMessage } from "views/views.slint";
import { NotificationView } from "views/notification_view.slint";

export { LauncherAdapter, ListAdapter, AppBarAdapter, NotificationAdapter, Icons }

export component MainWindow inherits Window {
    // launcher callback
    callback launcher-move-selection-left <=> LauncherAdapter.move-selection-left;
    callback launcher-move-selection-right <=> LauncherAdapter.move-selection-right;
    callback launcher-move-selection-up <=> LauncherAdapter.move-selection-up;
    callback launcher-move-selection-down <=> LauncherAdapter.move-selection-down;
    callback launcher-clear-selection <=> LauncherAdapter.clear-selection;
    callback launcher-open-page <=> LauncherAdapter.open-page;
    callback launcher-close-current-page <=> LauncherAdapter.close-current-page;
    callback launcher-move-left <=> LauncherAdapter.move-left;
    callback launcher-move-right <=> LauncherAdapter.move-right;
    callback launcher-move-up <=> LauncherAdapter.move-up;
    callback launcher-move-down <=> LauncherAdapter.move-down;
    callback launcher-on-enter <=> LauncherAdapter.on-enter;
    callback launcher-open-app <=> LauncherAdapter.open-app;
    callback launcher-close-list <=> LauncherAdapter.close-list;

    // list callbacks
    callback list-move-up <=> ListAdapter.move-up;
    callback list-move-down <=> ListAdapter.move-down;
    callback list-show-details <=> ListAdapter.show-details;
    callback list-move-left <=> ListAdapter.move-left;
    callback list-on-enter <=> ListAdapter.on-enter;

    // notification properties
    in property <[NotificationMessage]> notifications <=> NotificationAdapter.notifications;
    in property <NotificationMessage> recent-notification <=> NotificationAdapter.recent-notification;
    in property <bool> notification-show-recent <=> NotificationAdapter.show-recent;

    // launcher properties
    in property <[[Bubble]]> launcher-bubbles <=> LauncherAdapter.bubbles;
    in property <[Bubble]> launcher-pages <=> LauncherAdapter.pages;
    in property <int> launcher-current-bubble-page <=> LauncherAdapter.current-bubble-page;
    in property <int> launcher-current-page <=> LauncherAdapter.current-page;
    in property <bool> launcher-show-list <=> LauncherAdapter.show-list;

    // list properties
    in property <[[ListItem]]> list-items <=> ListAdapter.list-items;
    in property <string> list-title <=> ListAdapter.title;
    in property <brush> list-background <=> ListAdapter.background;
    in property <int> list-current-page <=> ListAdapter.current-page;
    in property <string> list-sub-title <=> ListAdapter.sub-title;

    // app bar properties
    in property <string> app-bar-current-time <=> AppBarAdapter.current-time;

    title: "vita";
    width: 960px;
    height: 544px;
    background: Theme.palette.background-gradient;

    forward-focus:  i-launcher-view;

    i-launcher-view := LauncherView {}

    NotificationView {
        width: 100%;
        height: 100%;
    }
}
