// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

import { Theme } from "theme.slint";

export component PathButton {
    callback clicked <=> i-touch-area.clicked;

    in property <string> path;
    in property <brush> fill <=> i-path.fill;

    width: 32px;
    height: 32px;

    i-path := Path {
        commands: root.path;

        animate opacity { duration: Theme.animations.medium; }
    }

    i-touch-area := TouchArea {}

    states [
        pressed when i-touch-area.pressed : {
            i-path.opacity: 0.0;
        }
    ]
}