// SPDX-FileCopyrightText: 2022 Florian Blasius <co_sl@tutanota.com>
// SPDX-License-Identifier: MIT

struct Spacings {
    small: length,
    medium: length,
    large: length,
    extra-large: length
}

struct Sizes {
    bubble: length,
    pageination-bubble: length,
}

struct Animations {
    medium: duration,
    fast: duration
}

struct Palette {
    gradient-white-right: brush,
    gradient-white-left: brush
}

export global Theme {
    out property <Sizes> sizes: {
        bubble: 128px,
        pageination-bubble: 8px,
    };

    out property <Spacings> spacings: {
        small: 4px,
        medium: 8px,
        large: 16px,
        extra-large: 64px,
    };

    out property <Animations> animations: {
        fast: 150ms,
        medium: 200ms,
    };

    out property <Palette> palette: {
        gradient-white-right: @linear-gradient(90deg, #ffffff00 0%, #ffffff 100%),
        gradient-white-left: @linear-gradient(90deg, #ffffff 0%, #ffffff00 100%),
    };
}